### ISSUE TITLE
[enhancement] Don't require users to login to Google

### ISSUE THREAD

**Issue by jyn514** [NovaViper/TrinityLocker#7]
During onboarding, the first thing a user sees is @+string/signInScreenAccept, in file [strings.xml](https://github.com/NovaViper/TrinityLocker/blob/master/app/src/main/res/values/strings.xml). Please allow users to store config locally instead of in the cloud.

**Comment by NovaViper** [comment]
I am currently rewriting the app completely from the ground up. I have (as of now) completely removed the option to sign into your Google account, thus allowing all configurations to be saved on the device 👍
